version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified
      shell: powershell.exe

    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout:
          path: C:\Users\circleci\project
      - restore_cache:
          keys:
            - pw
      # - run:
      #     name: "Install node"
      #     command: nvm install 14.16.1
      # - save_cache:
      #     key: nodeNvm
      #     paths:
      #       - C:\ProgramData\nvm\v14.16.1
      - restore_cache:
          keys:
            - nodeNvm
      - run:
          name: "Use node"
          command: nvm use 14.16.1
      - run:
          name: "Install project dependencies"
          command: npm install
      - save_cache:
          key: pw
          paths:
            - C:\Users\circleci\AppData\Local\ms-playwright
      - run: npx playwright --version
      - run: node ./demos/mobile.mjs

      - store_artifacts:
          path: ./example.png