version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    docker:
    - image: mcr.microsoft.com/playwright:focal
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npx playwright --version
      - run: node ./demos/mobile.mjs

      - store_artifacts:
          path: ./example.png
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only: /ci\/.*/