version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    docker:
    - image: mcr.microsoft.com/playwright:focal
    steps:
      - checkout
      - run: npx playwright --version
      - run: node ./demos/mobile.mjs