version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '14.16.1'
    steps:
      - checkout
      - run: 
            command: sudo apt-get update
      - run:
            name: Install packages for correct work with Playwright
            command: |
              sudo apt-get update && sudo apt-get install -y libwoff1
              sudo apt-get -y install libopus0
              sudo apt-get -y install libwebp6
              sudo apt-get -y install libwebpdemux2
              sudo apt-get -y install libenchant1c2a
              sudo apt-get -y install libgudev-1.0-0
              sudo apt-get -y install libsecret-1-0
              sudo apt-get -y install libhyphen0
              sudo apt-get -y install libgdk-pixbuf2.0-0
              sudo apt-get -y install libegl1
              sudo apt-get -y install libgles2
              sudo apt-get -y install libevent-2.1-6
              sudo apt-get -y install libnotify4
              sudo apt-get -y install libxslt1.1
              sudo apt-get -y install libvpx5
              sudo apt-get -y install gstreamer1.0-gl
              sudo apt-get -y install gstreamer1.0-plugins-base
              sudo apt-get -y install gstreamer1.0-plugins-good
              sudo apt-get -y install gstreamer1.0-plugins-bad
              sudo apt-get -y install libgbm1
      - node/with-cache:
          steps:
            - run: npm install
      - node/with-cache:
          steps:
            - run: npm install playwright
      - run: npx playwright --version
      - run: node ./demos/mobile.mjs