version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '14.16.1'
    steps:
      - checkout
      - run:
            name: Install packages for correct work with Playwright
            command: |
              apt-get update && apt-get install -y python3.8 python3-pip && \
              update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1 && \
              update-alternatives --install /usr/bin/python python /usr/bin/python3 1 && \
              update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
      - node/with-cache:
          steps:
            - run: npm install
      - node/with-cache:
          steps:
            - run: npm install playwright
      - run: npx playwright --version
      - run: node ./demos/mobile.mjs